baseURL = "http://example.org/"

DefaultContentLanguage = "en"

[params.navigation]
help  = "Help"

[Languages]
[Languages.en]
title = "My blog"
weight = 1
[Languages.en.params]
linkedin = "english-link"

[Languages.fr]
copyright = "Tout est à moi"
title = "Mon blog"
weight = 2
[Languages.fr.params]
linkedin = "lien-francais"
[Languages.fr.navigation]
help  = "Aide"
languageCode = "en-us"
title = "Tower Winery"
[params]
	description = "Friendship and passion to produce great wines"

[[params.social]]
	title = "email"
	icon = "envelope-o"
	url = "mailto:darrenspruce@gmail.com"
